### ISSUE TITLE
貌似下拉刷新是有问题的

### ISSUE THREAD

**Issue by Chaunjie** [songhaoreact/weixin#1]
下拉刷新无论请没请求完成，貌似3秒都会恢复，请问你有解决方案吗？

**Comment by Chaunjie** [comment]
@songhaoreact

**Comment by songhaoreact** [comment]
@Chaunjie  这个下拉是手动暂停的啊，请求完数据 ，状态更新完之后才会手动暂停，如果不手动暂停
下拉会一直存在啊

**Comment by Chaunjie** [comment]
@songhaoreact 我刚刚试了下，在IDE下面是会自动恢复的，但是在真机情况下面是正常的需要手动恢复

**Comment by songhaoreact** [comment]
@那就是ide的bug了， 真机ok就可以

**Comment by songhaoreact** [comment]
@Chaunjie  那可能就是ide的bug了 真机可以就ok

**Comment by Chaunjie** [comment]
感觉玩这个限制很多，完全依赖微信官方的而不是社区的力量。
