### ISSUE TITLE
如何运行? 你的项目

### ISSUE THREAD

**Issue by fengsong97** [songhaoreact/weixin#2]

**Comment by songhaoreact** [comment]
@fengsong97  可以真机运行 也可以用微信开发者工具运行
您是在运行过程中出错了么

**Comment by fengsong97** [comment]
必须绑定小程序之后才能运行吗 ?  
用web服务器 启动,ranhou 微信开发这平台访问吗 ?

**Comment by fengsong97** [comment]
必须绑定小程序之后才能运行吗 ?  
用web服务器 启动 ,  然后用微信开发工具访问吗 ?

**Comment by fengsong97** [comment]
不好意思 , 我不太明白 怎么启动你的项目 , 安装启动能说的细一点吗?

**Comment by songhaoreact** [comment]
@fengsong97  把我的代码clone下来之后， 放到微信开发者工具里面就可以用模拟器运行，如果是真机运行的话 需要appid ，要注册微信小程序账号（目前只支持企业 组织 不支持个人）。
